Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
  DynamoDBCostEstimateRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
          - 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
      - PolicyName: AthenaCloudWatchRole
        PolicyDocument:
          Statement:
          - Action:
            - 'cloudwatch:Describe*'
            - 'cloudwatch:Get*'
            - 'cloudwatch:List*'
            - 'athena:GetQueryExecution'
            Resource: '*'
            Effect: Allow
          - Action:
            - 'glue:*'
            - 'athena:*'
            Resource: '*'
            Effect: Allow
          - Action:
            - 's3:*'
            Resource:
            - !GetAtt
              - S3Bucket
              - Arn
            - !Sub
              - 'arn:${AWS::Partition}:s3:::${S3Bucket}/*'
              - bucketName: !Ref S3Bucket
            Effect: Allow
      Tags:
      - Value: SAM
        Key: 'lambda:createdBy'
  DynamoDBCostEstimateFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Code:
        S3Bucket: !Ref LambdaFunctionS3Bucket
        S3Key: !Ref LambdaFunctionS3Key
      Description: ''
      MemorySize: 4096
      Timeout: 900
      Role: !GetAtt
      - 'DynamoDBCostEstimateRole'
      - Arn
      Environment:
        Variables:
          ATHENA_BUCKET: !Ref S3Bucket
          ATHENA_PREFIX: !Ref S3Prefix
          ATHENA_DATABASE: !Ref AthenaDatabase
          ATHENA_TABLENAME: !Ref AthenaTableName
      Layers:
      - !Join
        - ':'
        - - 'arn:aws:lambda'
          - !Ref 'AWS::Region'
          - '336392948345:layer:AWSSDKPandas-Python38:3'
Parameters:
  S3Prefix:
    Default: dynamodb_estimate
    Type: String
    Description: The prefix within Output Bucket where this function can store result.
  AthenaDatabase:
    Default: default
    Type: String
    Description: Athena Database name
  AthenaTableName:
    Default: dynamodb
    Type: String
    Description: Athena Table Name to create for accessing  Metrics and Estimates
  LambdaFunctionS3Key:
    Type: String
    Description: S3 Key to the Lambda Function Zip file.
  LambdaFunctionS3Bucket:
    Type: String
    Description: The S3 Bucket name hosting the Lambda Function Code.
